import theStore from '@/ui/store';
import { register } from 'register-service-worker';

/** @fileOverview Handles starting and interacting with the service worker. Mostly generated by vue-cli. */

/* tslint:disable:no-console */


if (process.env.NODE_ENV === 'production') {
   register(`${process.env.BASE_URL}service-worker.js`, {
      ready() {
         console.log('SW: App is being served from cache by a service worker.');
      },
      registered(_registration) {
         console.log('SW: Service worker has been registered');
      },
      cached(_registration) {
         // TODO: This doesn't seem to work :()
         console.log('SW: Content has been cached for offline use');
         theStore.addDismissableMessage('info', 'App is now cached for offline use!');
      },
      updated(_registration) {
         console.log('SW: New content is available; please refresh');
         theStore.updateAvailable = true;
      },
      offline() {
         // TODO: Looks like this is never called in production - remove
         console.log('SW: No internet connection found. App is running in offline mode.');
         theStore.addDismissableMessage('warning', 'Offline mode - changes will sync later');
      },
      error(error) {
         console.error('SW: Error during service worker registration:', error);
      },
   });
}
